#!/usr/bin/env python
import sys, os, Tkinter, Pmw, Tix
from optparse import OptionParser
from fbMainGui import fbMainGui

def main():
    root = Tix.Tk()
    Pmw.initialise(root)

    parser = OptionParser(usage="usage: %prog [-d arg1,arg2,arg3,...]")
    parser.add_option("-d", "--dirs",
                      action="store", type="string", dest="dirList", default="", metavar="DIRS",
                      help=("Comma-delineated (no spaces) list of directories to be pre-loaded" +
                            " into the Selected Experiments list."))

    (options, args) = parser.parse_args()

    if len(options.dirList) > 0:
        dirs = options.dirList.strip(",").split(",")
    else:
        dirs = []

    browser = fbMainGui(root, initExpDirs=dirs)
    root.mainloop()

if __name__=='__main__': main()